### ISSUE TITLE
module 'torchaudio' has no attribute 'transforms'

### ISSUE THREAD

**Issue by yiyouls** [DinoMan/speech-driven-animation#10]
did i installed the wrong version of torchaudio?

**Comment by delapecci** [comment]
@yiyouls  same error, what about the solution?
I tried to uninstall torch@1.1 and downgrade to torch@1.0.1 and torchvision@0.2.1, checkout torchaudio@0.2 and install it, but got another error: 
<img width="1389" alt="图片" src="https://user-images.githubusercontent.com/2783025/60488644-0ce7dd80-9cd5-11e9-822d-6d192339d1a1.png">

**Comment by DinoMan** [comment]
Ok it seems that the latest torchaudio is not compatible with torch 1.1. (pytorch/audio#121) The sda library can work without torchaudio so I will remove it since it has been giving people headaches. I'll inform you once I've done it

**Comment by mrcoffeecoup** [comment]
Torchaudio has been removed as a dependency and the no_torchaudio_dependecy branch merged to master
