### ISSUE TITLE
Audio is not correctly normalised without using torchaudio

### ISSUE THREAD

**Issue by DinoMan** [DinoMan/speech-driven-animation#16]
It seems that the audio is not correct when I dont use torchaudio. I had not tested this functionality well enough since I always use the torchaudio version, which worked fine. It probably has to do with the normalisation not being correct. I'll investigate and update this issue when done

**Comment by DinoMan** [comment]
Hmm got it. It seems that I was scaling the audio differently to torchaudio (which was used for training). When not using torch audio I was scaling by a factor of 2. I'll make a branch and test for a few days and then merge onto master.

**Comment by mrcoffeecoup** [comment]
This has been merged to master now and seems to work quite well
