### ISSUE TITLE
Bad perfomance on a new data

### ISSUE THREAD

**Issue by zhumazik** [DinoMan/speech-driven-animation#2]
Sorry for the new issue :))

The model runs well on a sample image. But on the new images it shows quite bad results :(
The videos are too blurry even if I take high resolution photos.

Is it possible to fix it? 
Thanks.

**Comment by DinoMan** [comment]
Hi,
Which model do you use? They are trained on different datasets.the one trained on grid has only seen 15 faces during training. It can generalize reasonably for unseen faces from the grid dataset (which have similar background and lighting) but not so well for in the wild photos. ideally for that you will need the model trained on LRW but we haven't uploaded this yet. As an intermediate solution you could use the model trained on crema-d which has seen more identities during training. In short you must be a bit more patient until I make the lrw model available online and then you can do any in the wild photo.

**Comment by zhumazik** [comment]
Thanks. I used grid model. 
I promise I will be patient :).
