### ISSUE TITLE
A question about frame discriminator in the paper.

### ISSUE THREAD

**Issue by dpsfigo** [DinoMan/speech-driven-animation#23]
Hi,it's realy a good job you have done! When i was reading the paper, i have a question about the frame discriminator, in your paper , it says:
```
the frame discriminator determines whether a frame is real or not, and the original still frame is used as a condition in this network.
```
so what's the frame discriminator input,  paired images, or a sequence of images? i wonder how does it work with the sequence discriminator?

**Comment by DinoMan** [comment]
The frame discriminator takes in pairs of images (the first image of the sequence and q random image from the real or generated video). The two discriminators work independently to each other. Basically you can think of them as two experts with different areas of expertise judging the generated content.

**Comment by dpsfigo** [comment]
I see, thank you so much!!!
