### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.  

### ISSUE THREAD

**Issue by anthonyyuan** [DinoMan/speech-driven-animation#25]
_pickle.UnpicklingError: invalid load key, 'v'.  when I use va = sda.VideoAnimator(gpu=-1)# Instantiate the aminator

**Comment by avisekiit** [comment]
@anthonyyuan 
I am also getting the same error. Were you able to solve it.
I git cloned it and NOT git lfs.
Then I downloaded the .dat files from the Google Drive Link.
Still getting the  same error.

Thanks,
Avisek

**Comment by javaintheuk** [comment]
Hi,

Same problem here, it wont's pass this:

va = sda.VideoAnimator(gpu=0, model_path="crema")

An solution please? thanks

**Comment by kingjr** [comment]
Same problem here

**Comment by javaintheuk** [comment]
Update: I fixed it by using the right paths to the files and be sure you are on the right directory too, ie: cd /var/speech-driven-animation
