### ISSUE TITLE
Would you release a model which could generate higher resolution video?

### ISSUE THREAD

**Issue by chikiuso** [DinoMan/speech-driven-animation#27]
Hi, I understand your concern of not releasing the training code. Could you release a model which could generate higher resolution video? I would like to evaluate the details of the video, thanks for your help!

**Comment by DinoMan** [comment]
Hi, Yes larger Res models are in the plan. Maybe in a few months I will have 4x higher resolution for the grid model. This is not a priority task for me at the moment so I'm afraid the timeline on those is a bit vague. I'll keep this issue open and post once I have an update.

**Comment by chikiuso** [comment]
Hi DinoMan, thanks for your quick response and your great works, inspiring!

**Comment by chikiuso** [comment]
Hi @DinoMan, is it possible I could have a look of the training code? my email is : chkso@ouhk.edu.hk, thanks!
