### ISSUE TITLE
Is there any requirement to the input image?

### ISSUE THREAD

**Issue by yipgit** [DinoMan/speech-driven-animation#28]
Is there any requirement to the input image? I used another image to generate video myself, by the face in the video is broken and not distingushable. I 've tried three models with different pictures, the effect is not satisfied. Is there any requirement on the image input?
One more question, could you please release the model LRW?

**Comment by DinoMan** [comment]
There is no requirement for the image. The library will align the face by itself. The LRW model is the one that has seen many faces during training and can therefore work in in the wild scenarios (like the ones I posted on youtube). However we have decided not to release this model yet. If something changes and we decide to release the LRW model we will let you know here.

The existing models will work on unseen faces taken from the same dataset. In some few cases they might also work on other faces. However if your face is very different from those in the training set I'm afraid it wont work.

**Comment by yipgit** [comment]
Thank you for your quick response. I saw the closed issues describing the same. 
Thank you.
