### ISSUE TITLE
Unfortunately torchaudio is not supported on Windows

### ISSUE THREAD

**Issue by Neltherion** [DinoMan/speech-driven-animation#3]
As the title says...

**Comment by zhumazik** [comment]
Just comment all the lines with "torchaudio" in "sda.py". It's not needed if you call VideoAnimator this way:
`
import sda
import scipy.io.wavfile as wav
from PIL import Image
va = sda.VideoAnimator(gpu=0)# Instantiate the aminator
fs, audio_clip = wav.read("example/audio.wav")
still_frame = Image.open("example/image.bmp")
vid, aud = va(frame, audio_clip, fs=fs)`

**Comment by DinoMan** [comment]
The new version has no dependency on torchaudio so this can be closed
