### ISSUE TITLE
How to run on CPU

### ISSUE THREAD

**Issue by shrnjad** [DinoMan/speech-driven-animation#38]
I do not have a CUDA device, when running the example, I get this error:

`AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'`

How can I run the network on the CPU? What is the syntax?

**Comment by DinoMan** [comment]
The default argument for the anmator is gpu=-1 so if you do:

va = sda.VideoAnimator()
instead of:
va = sda.VideoAnimator(gpu=0)

it will use the CPU.

**Comment by shrnjad** [comment]
Thank you!
