### ISSUE TITLE
Absurd Output with CREMA-D pre-trained checkpoint

### ISSUE THREAD

**Issue by avisekiit** [DinoMan/speech-driven-animation#39]
Dear Authors,
Thanks for open sourcing your work. 
I faced a strange issue. If I try to run the image.bmp (should not be related to any dataset, I guess) file with a .wav file from CREMA-D dataset, then the visual quality is too bad.  You can see an attached frame with this thread.
![Screenshot 2020-02-08 at 1 38 30 AM](https://user-images.githubusercontent.com/12903678/74062217-c8af7f00-4a13-11ea-94bb-a2df826b58e0.png)

I made sure to load the crema.dat file before running.
Is there any extra step to satisfactorily run your CREMA-D pre-trained model?

Thanks,
Avisek

**Comment by DinoMan** [comment]
The image is from grid so it will work with the grid model and the LRW model (not available publicly). Since the models in the small datasets are trained on few speakers they do not generalize well to subjects from different datasets. If you want to you can use the grid model with the example.

**Comment by avisekiit** [comment]
Dear @DinoMan 

Thanks for your reply. I also tried one of the subjects from CREMA-D. For example, I used dlib to detect and crop out a face from a video frame of subject 1057 and then resized to 128 (height) X 96 (width). But, still the output seems to weird. Is there any normalization/frontalization required after I detect and crop out the face with dlib?

Below is the input image to the network.

![ref_1057_cropped](https://user-images.githubusercontent.com/12903678/74066617-73786b00-4a1d-11ea-84de-b50927d12533.png)

**Comment by DinoMan** [comment]
The library will align and crop the face automatically so there is no need to do this. Just put any image that contains the face.

**Comment by avisekiit** [comment]
Ok. So you are suggesting that I can just feed in the entire frame as it is without externally worrying about face detection. ?
Let me try this way. Also, below is the bare minimum code I am using to get some visual results. Does it look Ok to you ?
import sda
subject="1057"
va = sda.VideoAnimator(gpu=-1, model_path="crema")# Instantiate the animator
vid, aud = va("crema_ref_frames/ref_{}_cropped.bmp".format(subject), "example/{}.wav".format(subject))
print("Shape:",vid.shape)
va.save_video(vid, aud, "generated_{}.mp4".format(subject))

`

`

**Comment by DinoMan** [comment]
Yes the code looks fine to me. The library will download a face alignment library and use it to align the face. It should just be like the example in the documentation.

**Comment by avisekiit** [comment]
Thanks for your quick responses. So I managed to get a more decent video this time.
Does it look OK to you.

Anchor frame link: https://drive.google.com/open?id=1AUrhT5PsRWJd-XOxA64Eeje7OVAaJ78e

Audio Link: https://drive.google.com/open?id=1QAejDExnD0ZmZTpnDYG6lFP-4rLsQJOM
Generated Video Link: https://drive.google.com/open?id=1pZN09bDGBty4HJe60MVj6ivgtj-K6WwH

**Comment by DinoMan** [comment]
Yeah that is a plausible result. Some of the videos won't be very good. Starting from a frame with closed mouth sometimes might get you a slightly better result.

**Comment by avisekiit** [comment]
Ok. Thanks for all the help.
Closing this issue now.
Once again, congrats on the awesome work!!!

**Comment by avisekiit** [comment]
Dear @DinoMan 
Just re-opening this thread to re-assure some observations. I concatenated the sentences of a given subject and made a compact .wav file. Then I fed the frame of that same person to the network. I can see that for first 4-5 seconds, the visual quality is OK, but then the visual sequence is totally off-sync.
Do you think the model will not work if we just stich the audios together. Here are two output video links. Keenly looking forward to your expert thoughts on this:

Video 1 Link: https://drive.google.com/open?id=1Ma5RqCTbPIghaK8ee2mWB5k2KHiYjibo

Video 2 Link: https://drive.google.com/open?id=1VY5bhT5cfdTBxaX-KwMdRn1zOc2eVJ08

**Comment by DinoMan** [comment]
Ok, I think I have an explanation. The model does indeed tend to generate some artifacts the longer the sequence lasts and in your case you are using very large sequences. This deterioration in performance could be in part because the model sees 3-second clips and not minutes. Although the model has been designed to deal with variable length perhaps GRUs are practically not great at extrapolating that far into the future (which I've also seen in other applications too). 

On a more practical note perhaps a solution could be that you generate multiple smaller clips but use the last generated frame as a starting point for the next generation. In this case, you would likely get a smooth result.

**Comment by avisekiit** [comment]
@DinoMan 
Thanks for your reply. So, in your paper, when you report the metrics, you usually run the models on each individual sentences and then average the performance across all video ?

**Comment by DinoMan** [comment]
Yes.

**Comment by avisekiit** [comment]
Thanks again for all your help.
Closing the issue now.
Cheers!!!
