### ISSUE TITLE
Downloading Models?

### ISSUE THREAD

**Issue by Neltherion** [DinoMan/speech-driven-animation#4]
How can I download the models? Currently there's only `*.dat` files in the `data` folder.

**Comment by DinoMan** [comment]
Hi I have reached the bandwidth and storage limit for git lfs. I think that when that happens it doesn't download the files any more. I was not aware of this and will be looking into migrating the models somewhere else. I am also away on vacation now but will be looking into this once I'm back and will update this issue once I have performed the migration.

**Comment by skunkwerk** [comment]
I think I'm having the same issue - I've installed lfs, but all I see are the .dat files in the folder.  I think that's causing this error when I try to run the example:

>>> va = sda.VideoAnimator(gpu=0)# Instantiate the aminator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skunkwerk/speech-driven-animation/sda/sda.py", line 109, in __init__
    model_dict = torch.load(model_path, map_location=lambda storage, loc: storage.cuda(gpu))
  File "/home/skunkwerk/venv/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/skunkwerk/venv/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by kongbb1** [comment]
use git lfs, i can not get the model files, use github desktop tool i can get them, but with the hint: Resolving deltas, wait for a long time, the model download is begin to work

**Comment by xingmegshuo** [comment]
> Hi I have reached the bandwidth and storage limit for git lfs. I think that when that happens it doesn't download the files any more. I was not aware of this and will be looking into migrating the models somewhere else. I am also away on vacation now but will be looking into this once I'm back and will update this issue once I have performed the migration.

Now, where should I get the model

**Comment by DinoMan** [comment]
I have postponed doing this due to heavy workload. I will try to migrate the models to a different storage within the next days. Please be patient until then.

**Comment by xingmegshuo** [comment]
> 由于工作量大，我已推迟这样做。我将在接下来的几天中尝试将模型迁移到其他存储。请耐心等待。

Thank you very much, can you email me the model first?

**Comment by DinoMan** [comment]
I have moved the models to Google Drive to cope with the high demand.
