### ISSUE TITLE
CAN YOU PLEASE OPEN SOURCE THE TRAINING CODE 

### ISSUE THREAD

**Issue by ved3prakas** [DinoMan/speech-driven-animation#49]
A similar type of project work we have got for custom training of a person who can read from text file & generate the realistic facial video. 

If you please open source the code lots of people get ideas about how to custom train the model.

**Comment by ved3prakas** [comment]
can you please reply Denoman

**Comment by DinoMan** [comment]
This has been asked and answered before on issue #17. As I mentioned in that issue this is a speech-driven animation library and at the moment there is no plan to release the source code.

**Comment by ved3prakas** [comment]
Thank you for your quick response .
