### ISSUE TITLE
Video Quality

### ISSUE THREAD

**Issue by shahriarshakil0** [DinoMan/speech-driven-animation#66]
How can i improve the generated video quality ?

**Comment by Dileeprocky** [comment]
@shahriarshakil0  bro did u find the way to increase resolution

**Comment by shahriarshakil0** [comment]
Sorry bro. I can't find it.

**Comment by Dileeprocky** [comment]
@shahriarshakil0  I found a way to increase the scale but not quality I think trained dataset is 96x128 res so we can't increase res but if we want we need to create one trained dataset of high res

**Comment by shahriarshakil0** [comment]
Yeah. Hopefully it will be working.

**Comment by DinoMan** [comment]
You are right the resolution unfortunately can't increase for these models since they are trained at 96x128. The scale just upscales the video.
