### ISSUE TITLE
Face Alignment library issue

### ISSUE THREAD

**Issue by kundan121** [DinoMan/speech-driven-animation#73]
Currently your VideoAnimator doesn't work as you are using "face_alignment.LandmarksType._2D" object which currently doesn't exist.
When I used your repository, I got an error due to this object.

I have fixed this error for me. As "face-alignment" library is being updated so we also need to update this. 

Please add me as a contributor, so that I can create a pull request to fix this issue.

**Comment by weirui-kong** [comment]
In `sda.py`, just simply change `face_alignment.LandmarksType._2D` to `face_alignment.LandmarksType.TWO_D`.

I am using Python 3.11 and all the dependencies are the latest version. Maybe some of them changed attributes in the code.

**Comment by DinoMan** [comment]
Thanks for pointing out the issue I have fixed it now.
